### ISSUE TITLE
Selecting fields within Iframe

### ISSUE THREAD

**Issue by meinzeugde** [form-o-fill/form-o-fill-chrome-extension#82]
Hello,

is there a way to have form input fields within an Iframe selected?

Apparently it's always throwing me the message that the input can't be found, whereas when i use the Dev-Console and use the internal jQuery-Selector method it works.

There are also no concerns about the same-origin-policy, because it's the same server.
I also have no (effortless) option to avoid the Iframe.

![browser-dev-console](https://cloud.githubusercontent.com/assets/6060660/20891938/976b003e-bb0c-11e6-89ee-4a54d9727395.PNG)
![rules](https://cloud.githubusercontent.com/assets/6060660/20891937/976a5dfa-bb0c-11e6-9708-2dacb52cfc66.PNG)

**Comment by meinzeugde** [comment]
These are the errors:

![error](https://cloud.githubusercontent.com/assets/6060660/20892004/cb70ec72-bb0c-11e6-81e9-9871012bd2da.PNG)

**Comment by thenoseman** [comment]
Hi,

currently there isn't a way to easily access/fill content that resides in an <iframe>.
The only way seems to be using something like `document.getElementById('iframe').contentWindow.document.body` or `jQuery("#iframe").contents().find()` via JS in a value function.

Since this is a very good idea I'll have a go at this.
I think I'll introduce a new rule flag. 

What do you think?

```
"within": "#iframe",
"selector": ".some-class",  // <-- Will fill ".some.class" in "#iframe"
"value": "123"
```

**Comment by meinzeugde** [comment]
looks good :D

**Comment by thenoseman** [comment]
It's already live in version 3.2.0. Please update and try it out :)
